# Generated by Django 6.1.1 on 2026-09-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='place',
            new_name='marks',
        ),
    ]
